closeoutTableId=GrantorCloseOutRequest
closeoutApproverTableId=GrantorCloseoutRequestRolesAndResponsibilities
#grantsTableId=ActiveGrants
grantsTableId=GrantorActiveGrants
pendingTaskTableId=PhasePendingTasks
recipientsGrantTableId=RecipientActiveGrants
awardTableId=RecipientsRelatedAwards1
closeoutSupportingDocumentChecklist=CloseoutChecklists
closeoutPeerReviewTableId=GrantorCloseoutPeerReview
closeoutFilesTableId=GrantorCloseoutFiles
closeoutAddFileTableId=WorkspaceFilesUpload
closeoutFundingAccountsTableId=CloseoutFundingAccounts
#homePendingTaskTableId=PendingTasks
homePendingTaskTableId=HomePendingTasks
externalHomePendingTasktableId=PendingTasks
ProjectPeriodCloseoutTableId=ProjectPeriodCloseoutGrantor
CloseoutTableId=AllCloseouts
closeoutPendingAmendmentRequestsTableId=GrantCloseOutAmendmentRequestGrantor
closeoutSiteVisitTableId=GrantorSiteVisitsAward
RequestTabCloseoutRequestTableId=GrantorCloseOutRequest
ExternalCloseoutDetailsTableId=ExternalCloseoutFiles
CloseoutDetailsTableId=GrantorCloseoutFiles
CloseoutRelatedSubAwardsTableId=FundingAccountRelatedAwards
RecipientCloseoutRequestTableId=RecipientsCloseOutRequestExternal
PendingSiteVisitDeskReviewTableId=SiteVisitsGrantorCloseoutGrid
snapshotHistoryTableId=toggleAttachmentsa0t4T000000YQT3QAO
closeoutNotesTableId=GrantortCloseoutContentNotes
closeoutPaymentRequestTableId=CloseOutPaymentRequestGrantor
closeoutOwnerTableId=GrantorCloseoutOwner
closeoutSourceTableId=CloseoutSourceOwnerReplace
closeoutTargetTableId=CloseoutTargetOwnerReplace
closeoutHistoryTableId=History
closeoutPendingProgressReportCloseoutTableId=RelatedGrantorProgressReportsPPCloseout
subrecipientBudgetSummaryFocusAreaTableId=RecipientsGrantFocusAreasCloseout
grantorBudgetSummaryFocusAreaTableId=Budgetsummarybyfocusareacloseout
subrecpientPendingTaskTableId=PhasePendingTasks
