participantsTableId=GrantorSiteVisitContacts
deskReviewContactsTableId=SelectSiteDeskReviewContacts
#approverDeskReviewTableId=flexGridGrantorSiteVisitRolesandResponsibilities
approverDeskReviewTableId=GrantorDeskReviewRolesandResponsibilities
correctiveTableId=GrantorSiteVisitFindingsGrid
reportsTableId=SVDRFormEnhancedTable
receipientTableId=GrantorSiteVisitFindingsGridRecipientEnhance
deskReviewCorrectiveTableId=SiteVisitCorrectiveActionsGrantorRecipientEnhanced
deskReviewGridViewTableId=LatestDeskReviewReportsGrid
monitoringTabPhasePendingTasks=PhasePendingTasks
awardDeskReviewTableId=SelectAwardSiteDeskReviews
associateAwardDeskReviewTableId=SiteVisitAssociatedAwards
reviewersFlexTableId=SiteVisitReviewerRoles
internalRelatedAwards1=RelatedAwards1
#internalActiveGrants=ActiveGrants
internalActiveGrants=GrantorActiveGrants
homePendingTasksTableId=HomePendingTasks
monitoringTabDeskReviewTableId=ApplicantDeskReviewReports
managementInitiateDRtableid=GrantorDeskReviewAward
activeGrantsTableId=GrantorActiveGrantsgrid
GrantsSubAwardsTableId=RelatedAwards1
deskReviewSourceTableId=SiteVisitSourceOwnerReplace
deskReviewTargetTableId=SiteVisitTargetOwnerReplace
deskReviewOwnerTableId=GrantorSiteVisitOwnerRoles
deskReviewHistoryTableId=History
deskReviewsFilesTableId=GrantorDeskReviewFiles
deskReviewNotesTableId=DeskReviewNotes
homeCompletedTaskTableId=PhaseCompletedTasks
deskReviewsAddFilesTableId=ExternalDeskReviewFiles
