focusAreaTableId=GrantorServiceAreas
relatedProgramsTableId=RelatedPrograms
FocusAreaFilesTableId=GrantorFocusAreaFiles
ActiveGrantsTableIdFocusArea=RelatedGrants
GrantsSubAwardsTableIdFocusArea=RelatedAwards1
SubAwardFocusAreaTableId=EnhancedGrantorAwardServiceAreas
