##########ContactsTableId######################
FDMTableId=FDMAnnouncementReviewSteps
FundingAccountTableId=FDMFundingAccountGrantor
RecommendedApplicationTableId=FundingDecisionMemoApplications
NonRecommendedApplicationTableId=FundingDecisionMemoNonRecommendApplication
InternalContactsTableId=InternalContacts
PotentialReviewerContactTableId=Reviewers

############subAward################################
FundingAccountInformationTableId=AwardFundingAccounts
SubAwardBudgetTableId=SubAwardBudgetCategoryFlexGrid
FederalProgramTavleTableId=RelatedFederalProgramForAward
SubAwardContactsTableId=SubawardContact

###########Home########################
PendingTaskAssignedToMeTableId=HomePendingTasks
PendingTaskAssignedByMeTableId=HomePendingTasksBy
CompletedTaskAssignedToMeTableId=HomePhaseCompletedTasks
SubrecipientOrganization=UserRegistration
SubrecipientIndRegistration=UserRegistrationIndApp
