deskReviewContactsTableId=GrantorSiteVisitOrganizationContactsGrid
#deskReviewContactsTableId=SelectSiteDeskReviewContacts
associateContactsId=SelectSiteDeskReviewContacts
#associateContactsId=GrantorSiteVisitOrganizationContactsGrid
approverSiteVisitTableId=GrantorDeskReviewRolesandResponsibilities
associateAwardId=SiteVisitOrganizationAwardsGrid
correctiveTableId=GrantorSiteVisitFindingsGrid
selectAwardId=SelectAwardSiteDeskReviews
reportsTableId=SVDRFormEnhancedTable
receipientTableId=GrantorSiteVisitFindingsGridRecipientEnhance
phasePendingTaskTableId=PhasePendingTasks
homePhasePendingTasks=PendingTasks
deskreviewPanelId=DeskReview
homeCompletedTaskTableId=HomePhaseCompletedTasks
orgDeskReviewNotesTableId=OrgDeskReviewContentNote
orgDeskReviewFilesTableId=OrgDeskReviewFilesGrid
orgDeskReviewPeerReviewTableId=SiteVisitReviewerRoles
participateassociateContactsId=GrantorSiteVisitOrganizationContactsGrid
approverDeskReviewTableId=GrantorDeskReviewRolesandResponsibilities
