kpiTableId=ProgressReportKeyOutcomesEnhanced
formTableId=FormEnhancedTablePR
progressReportFlexTableId=GrantorProgressReportsExternal
internalProgressReportFlexTableId=GrantorProgressReportsInternal
subrecipientPendingTaskTableId=PhasePendingTasks
pendingTaskTableId=PhasePendingTasks
approversTableId=ProgressReportsRolesandResponsibilities
subawardsTableId=RelatedAwards1
#awardKPITableId=inlineEditGridGrantorAwardKeyOutcomes
awardKPITableId=GrantorAwardKeyOutcomes
#activeGrantsTableId=ActiveGrants
activeGrantsTableId=GrantorActiveGrants
grantorGrantProgressReportTableId=CompletedReportingRequirementsReport
recipientAwardProgressReportTableId=RecipientProgressReportsAll
#recipientAwardProgressReportTableId=RecipientsCompletedReportingRequirementsReport
AwardProgressReportTableId=GrantorProgressReportsAll
progressReportsScheduleId=TnCSchedules
recipientActiveGrantId=RecipientActiveGrants
recipientsRelatedSubAwardsTableId=RecipientsRelatedAwards1
progressReportsTaskScheduleId=RelatedPRSchedules
monitoringScheduleGrantorTableId=MonitoringScheduleGrantor
recipientGrantProgressReportTableId=RecipientsCompletedReportingRequirementsReport
grantorProgressReportsTableId=GrantorProgressReportsAll
peerReviewersTableId=GrantorProgressReportReviewer
progressReportChecklistsTableId=ProgressReportChecklists
grantChecklistsTableId=GrantChecklists
ProgressReportChecklistTableId=ProgressReportChecklists
recipientActiveGrantTableId=RecipientActiveGrants
grantorProgressReportsExternalTableId=GrantorProgressReportsExternal
GrantorProgressReportReviewerTableId=GrantorProgressReportReviewer
budgetChangeTableId=RecipentAmendmentRequestBudgetGrid
#objectivesTableId=AwardStrategicGoalsObjectives
objectivesTableId=AwardStrategicGoalsObjectives
recipientAwardsTableId=RecipientsRelatedAwards2
awardKeyOutcomes=GrantorAwardKeyOutcomes
HomePendingTaskTableId=PendingTasks
RecipientSubAwardTableId=RecipientsRelatedAwards1
GrantsSubAwardsTableId=RelatedAwards1
AmendmentAttachmentTableId=GrantorAmendmentRequestFiles
RecipientProgressReportNotesTableId=RecipientProgReportNotes
progressReportChildScheduleId=RelatedPRSchedules
RecipientprogressReportScheduleTableId=TnCSchedules
RecipientProgressReportFilesTableId=GrantorProgressReportFiles
ProgressReportModalIframeId=GrantorReportingRequirementsiframeContentId
progressSourceTableId=ProgressReportsSourceOwnerReplace
progressTargetTableId=ProgressReportsTargetOwnerReplace
progressReportFilesTableId=GrantorProgressReportFiles
progressNotesTableId=ProgressReportContentNote
progressOwnerTableId=GrantorProgressReportsOwnerRoles
progressHistoryTableId=History
sf428cFormAttachmentTableId=SF428CFormFiles
sf425TransactionTableID=SF425Grid
sf425IndirectExpenseTableId=IndirectExpenseEnhancedGrantor
sf425AGrantCoveredTableId=SF425Atable
sf428SDetailIndividualTableId=DetailedIndividualItemTable
sf428AFederallyOwnedTableId=FederallyOwnerPropertyTable
sf271FormTableId=SF271GridProgressReport
GrantorNotesProgressReporttableId=ProgressReportContentNote
