FundingSource=FS-ST-002
ADMIN_EmailID=jeff.kumah@yopmail.com
FundingSourceTitle=Automation Permanent Funding Source
FundingAccount=FA-ST-40
FundingAccountName=Automation Permanent Funding Account
FocusAreaTitle=Automation Permanent Focus Area
FocusAreaTitle_2=Automation Permanent Focus Area2
StrategicPlan=REI Strategic Plan
StrategicGoal=REI Strategic Goals
StrategicObjective=REI Objective
StrategicGoal_2=Automation Permanent Strategic Goal
StrategicObjective_2=Automation Permanent Objective2
KPITitle=Automation Permanent KPI
InternalProgram=Automation Permanent Internal Program
InternalProgram_1=Automation Permanent Internal Program_1
InternalProgram_2=Automation Permanent Internal Program_2
InternalOrganization=Kansas Department of Education
SubrecipientOrg=SAN DIEGO ELECTRICAL TRAINING TRUST
Organization_School_District=Test District
RiskAssessmentOrg=Automation Permanent Organization for Risk Assessment
PM_EmailID=sarahpm.ksdeuat@yopmail.com
FO_EmailID=vectorfo.ksdeuat@yopmail.com
PO_EmailID=emailypo.ksdeuat@yopmail.com
