raPeerReviewFlexTableId=RiskAssessmentApproverRoles
monitotingTableRiskAssessmentFlexTableId=RiskAssessmentGridViewInternal
riskAssessmentGridViewExternalTableId=RiskAssessmentGridViewExternal
AwardRiskAssesmentTableId=AwardRiskAssessmentView
homePendingTaskTableId=HomePendingTasks
pendingTaskTableId=PhasePendingTasks
completedTaskTableId=PhaseCompletedTasks
attachmentsFlextableId=a151k000000nTz2AAE
amendmendRequestCreationTableId=GrantorAwardAmendmentRequest
organizationprofileviewTableId=AwardRiskAssessmentFlexGrid
riskAssSourceTableId=RiskAssessmentSourceOwnerReplace
riskAssTargetTableId=RiskAssessmentTargetOwnerReplace
riskAssOwnerTableId=GrantorRiskAssessmentOwnerRoles
riskAssNotesTableId=GrantorRistAssessmentContentNotes
riskIframeId=GrantorRiskAssessmentFilesiframeContentId
riskAssessmentHistoryTableId=History
riskAssSnapShotHistoryTableId=a0t4T000001rREuQAM
