amendmentRequestTableId=GrantorAwardAmendmentRequest
keyOutcomesTableId=GrantorAmendmentKeyOutcomes
goalsAndObjectivesTableId=GrantorAmendmentGoalsObjectives
approversTableId=AmendmentreqRolesAndResponsibilities
projectAreasTableId=AmendmentProjectAreasGrantor
objectivesTableId=SelectAmendmentGoals
TNCTableID=SelectAmendmentTermConditions
pendingTaskTableId=PhasePendingTasks
focusAreaTableId=SelectAmendmentGAT
fundingChangeApproversTableId=AmendmentreqRolesAndResponsibilities
budgetChangeTableId=RecipentAmendmentRequestBudgetGrid
amendmentLineItemsTableId=AmendmentLineItem
recipientActiveGrantsTableId=RecipientActiveGrants
recipientAwardsTableId=RecipientsRelatedAwards1
amendmentFundingAccountsTableId=AmendmentFundingAccounts
#grantorAmendmentRequestsTableId=GrantorAmendmentRequests
grantorAmendmentRequestsTableId=GrantorAmendmentRequests
grantorBudgetChangeTableId=AmendmentRequestBudgetGrid
recipientsAwardPaymentRequestsTableId=RecipientsAwardPaymentRequests
internalActiveGrants=GrantorActiveGrants
internalRelatedAwards1=RelatedAwards1
recipientKeyOutComes=RecipientAmendmentKeyOutcomes
FundingChangeFocusAreaTableId=AmendmentProjectAreasGrantor
RecipientKeyPersonalTableId=RecipientAmendmentContact
BudgetChangeTableId=RecipentAmendmentRequestBudgetGrid
AddLineItemForBudgetChangeTableId=AmendmentLineItem
AmendmentFundingAccountTableId=AmendmentFundingAccounts
AssociateFundingAccountTableId=SelectAmendmentFundingAccounts
recipientsSubawardTableId=RecipientsRelatedAwards2
recipientAwardAmendmentRequestTableId=RecipientAwardAmendmentRequest
AmendmentAttachmentTableId=GrantorAmendmentRequestFiles
AmendmentSpecialConditionTableId=GranteeTermsandConditionsAmendmentGrid
RecipientKPITableId=RecipientAmendmentKeyOutcomes
AmendmentKPITableId=GrantorAmendmentKeyOutcomes
RecipientAwardBudgetTableId=RecipientAwardBudgetCategoryFlexGrid
RecipientAttachmentTableId=ExternalAmendmentRequestFiles
RecipientKeyPersonalAssociateTableId=AssociateAmendtmentContacts
InternalKeyPersonalTableId=GrantorAmendmentContact
RecipientCarryForwardBudgetTableId=RecipientAmendmentRequestCarryForwardBudget
InternalCarryForwardBudgetTableId=AmendmentRequestCarryForwardBudget
RecipientParentCarryForwardBudgetTableId=RecAmendmentRequestCarryForwardBudget
RecipientPerformanceKPITableId=ProgressReportKeyOutcomesEnhanced
#InternalKPITableId=GrantorAwardKeyOutcomes
InternalKPITableId=GrantorAmendmentKeyOutcomes
GrantsBudgetCategoriesTableId=GrantBudgetCategoryFlexTableFlexToggle
GrantsActualBudgetPeriodTableId=GrantBudgetCategoryActualsFlexToggle
amendmentSourceOwnerTableId=AmendmentRequestSourceOwnerReplace
amendmentTargetOwnerTableId=AmendmentRequestTargetOwnerReplace
historyTableId=History
amendmentAddNotesTableId=AmendmentRequestContentNote
amendmentAddFilesTableId=GrantorAmendmentRequestFiles
amendmentOwnerTableId=GrantorAmendmentOwnerRoles
subrecipientProjectAreasTableId=RecipientProjectAreasGrantor
recipientSideAmendmentRequestTableId=RecipientAmendmentRequests
carryForwardFocusAreaTableId=RecipientAmendmentProjectAreasGrantorCarryForward
grantorCarryForwardFocusAreaTableId=AmendmentProjectAreasGrantorCarryForward
homeCompletedTaskTableId=HomePhaseCompletedTasks
homePendingTasksTableId=HomePendingTasks
subrecipientPendingTask=PhasePendingTasks
SubrecipientGrantAmendmentTableId=SubrecipientAmendmentRequest
SubrecipientgoalsAndObjectivesTableId=RecipientAmendmentGoalsObjectives
RecipientTermsandConditionsTableId=RecipientTermsandConditionsAmendment
SubrecipientAmendmentNotesTableId=SubrecipientAmendmentContentNotes