#fundingAccount=FA-ST-61
fundingAccount=FA-ST-196
# fundingAccount=FA-ST-01
fundingAccount1=FA-ST-197
qaOrgFundingAccount=FA-ST-22
fataSingleExternalFA=FA-FD-272
#Automation Permanent Funding Source
InternalProgram_NoFA=Automation Permanent Internal Program_NoFA
InternalProgram_AppSupportingDocYes=Automation Permanent App Supp Doc Yes
InternalProgram_PreAppSupportingDocYes=PROGRAM_FOR_PREAPP_SUPP_DOC_YES
ExternalProgram=Automation Permanent NGO Program
ClosedStateAnnouncement_ApplicationSubmittedToGrantor=Automation Permanent Closed Announcement Directed
Automation_Formula_Closed_Announcement_By_Applicant=Automation Permanent Closed Formula Announcement
ClosedStateFormulaAnn_ByApplicant_PreScreenReviewCompleted=Automation Permanent Closed Formula Ann-By Applicant
ClosedStateFormulaAnn_ByApplicant_FDMApproved=Automation Permanent FDM Approved Closed Formula Ann-By Applicant
ClosedStateFormulaAnn_ByApplicantAndFocusArea_PreScreenReviewCompleted=Automation Permanent Closed Formula Ann-By Applicant and Focus Area
ClosedStateFormulaAnn_ByApplicantAndFocusArea_FDMApproved=Automation Permanent FDM Approved Closed Formula Ann-By App and Focus Area
ArchivedStateFormulaAnn_ByApplicant=Automation Permanent Archived Formula Ann-By Applicant
ArchivedStateFormulaAnn_ByApplicantAndFocusArea=Automation Permanent Archived Formula Ann-By Applicant and Focus Area
SubrecipientOrgWithoutActiveRiskAssessment=Product Sub Recipient Test Organization
AutomationProgramNoSupportDoc=Automation Permanent No Supporting Doc Program
AutomationClosedSubAward=Automation Executable Award
ByApplicantAndFocusAreaYesClosedSubaward=Automation FDM Announcement Focus Area Yes
IndByApplicantAndFocusAreaYesClosedSubaward=Automation Ind FDM Announcement Focus Area
ByApplicantAndFocusAreaNoClosedSubaward=Automation FDM Announcement Focus Area No
CompetitiveClosedAward=Automation Closed Competitive Award
IndCompetitiveClosedAward=Automation Ind Closed Competitive Award
DirectedClosedAward=Automation Closed Directed Award
ByApplicantFocusYesClosedAwardDirectGrant=Automation By Applicant Closed Award
AdminByApplicantFocusYesClosedAwardDirectGrant=Automation By Applicant Admin Closed Award
INDAdminByApplicantFocusYesClosedAwardDirectGrant=Automation IND By Applicant Admin Closed Award
AdminByApplicantFocusNoClosedAwardDirectGrant=Automation By Applicant Focus No Admin Closed Award
INDAdminByApplicantFocusNoClosedAwardDirectGrant=Automation Ind By Applicant Focus No Admin Closed Award
ClosedAwardByAppDetailBudget=Automation Permanent Closed Award By App Details Budget Yes
ClosedIndAwardByAppDetailBudget=Automation Permanent Ind Closed Award By App Details Budget Yes
AdminByApplicantFocusAreaClosedAwardDirectGrant=Automation Permanent By Applicant Focus Area Admin Closed Award
StringOf100Chars=test1234567890095test123678912q3rt45y167y452h4y18k38sgqq116637sdget3467qwysgh3467iujfgvbfhtyyy345677
StringOf60Chars=test1234567890095test123678912test1234567890095test123678912
StringOf55Chars=test1234567890095test123678912test1234567890095test1236
StringOf35Chars=test1234567890095test123678912ut123
StringOf30Chars=test1234567890095test123678912
CompetitiveClosedAnnDetailBudgetYes=Automation Permanent Competitive Announcement Detail Yes
CompetitiveClosedAnnoucement=Automation Permanent Competitive Announcement closed state
closedAnnouncementForUndo=Automation Permanent Competitive Undo Announcement closed
#FormulaClosedAnnoucement=Formula Permanent Closed Annoucement
CompetitiveArchivedAnnoucement=Competitive Permanent Archived Annoucement
DirectedArchivedAnnoucement=Directed Permanent Archived Annoucement
AutomationExternalOrgApproved=Test Permanent External Organisation
AutomationExternalOrgSubmitforApproved=Test Permanent Organisation1
AutomationExternalOrgRejected=Test Permanent External Organisation2
AutomationExternalOrgInProgress=Test Permanent External Organisation3
AutomationPermanentApplicationReviewForGlobalSearch=Automation Permanent R-010709
AutomationPermanentApplicationReviewCompleted=Automation Permanent Review Completed
AutomationPermanentApplicationReviewDecline=Automation Permanent Review Decline
AutomationExpiredApplication=Automation Permanent Closed Announcement
AutomationPermanentLead=Automation Permanent Lead
AutomationPermanentPreApplication=Automation Permanent Pre Application
AutomationPermanentPreApplication2=Automation Permanent Pre Application2
AutomationPermanentLeadPreApplicationExpired=Automation Runtime Opportunity96080
AutomationPermanentPreApplicationExpiredStatus=Automation Permanent Pre Application Expired Status
AutomationPermanentLeadPreApplicationAllSettingNo=Automation Permanent Lead Pre Application All Setting No
govGrantOpportunityConvertToApplication=Grants.gov Program Management Office
AutomationPermanentApplicationStaticRecord=Automation Permanent Application Static Record
govGrantOpportunityConvertToprepplication=AN--820
300Char=In the heart of a bustling city, beneath the glowing lights, a small caf� stands as a haven for the weary traveler. The aroma of freshly brewed coffee fills the air, inviting everyone who walks by to step in and enjoy a moment of peace, warmth, and the comforting hum of quiet conversation. Test Che.
60Char=aBcDeFgHiJkLmNoPqRsTuVwXyZAbCdEfGhIjKlMnOpQrStyruiopikjghrytut
StringOf18Chars=200000000000000.30
grantorAutomationOrg=Test Automation Organization
externalAutomationOrg=Test With Automation PM
focusArea=Automation Permanent Focus Area
focusArea2=Automation Permanent Focus Area2
strategicPlanObjective=Automation Permanent Objective
KPITitle=Automation Permanent KPI
subrecipientAutomationOrg=SAN DIEGO ELECTRICAL TRAINING TRUST

