fundingAccount=FA-ST-03
fundingAccount1=FA-ST-04
#Automation Permanent Funding Source
ClosedStateAnnouncement_ApplicationSubmittedToGrantor=Automation Directed Announcement
Automation_Formula_Closed_Announcement_By_Applicant=AN-REI-062
ClosedStateFormulaAnn_ByApplicant_PreScreenReviewCompleted=Automation Permanent Closed Formula Ann-By Applicant
ClosedStateFormulaAnn_ByApplicant_FDMApproved=Automation Permanent Closed Formula Ann-By Applicant
ClosedStateFormulaAnn_ByApplicantAndFocusArea_PreScreenReviewCompleted=Automation Permanent Closed Formula Ann-By Applicant and Focus Area
ClosedStateFormulaAnn_ByApplicantAndFocusArea_FDMApproved=Automation Permanent Closed Formula Ann-By Applicant and Focus Area1
ArchivedStateFormulaAnn_ByApplicant=Automation Permanent Archived Formula Ann-By Applicant
ArchivedStateFormulaAnn_ByApplicantAndFocusArea=Automation Permanent Archived Formula Ann-By Applicant and Focus Area
SubrecipientOrgWithoutActiveRiskAssessment=Product Sub Recipient Test Organization
AutomationProgramNoSupportDoc=Automation Permanent No Supporting Doc Program
AutomationClosedSubAward=Automation Executable Award
ByApplicantAndFocusAreaYesClosedSubaward=Automation FDM Announcement Focus Area Yes
IndByApplicantAndFocusAreaYesClosedSubaward=Automation Ind FDM Announcement Focus Area
ByApplicantAndFocusAreaNoClosedSubaward=Automation FDM Announcement Focus Area No
CompetitiveClosedAward=Automation Closed Competitive Award
IndCompetitiveClosedAward=Automation Ind Closed Competitive Award
DirectedClosedAward=Automation Closed Directed Award
ByApplicantFocusYesClosedAwardDirectGrant=Automation By Applicant Closed Award
AdminByApplicantFocusYesClosedAwardDirectGrant=Automation By Applicant Admin Closed Award
INDAdminByApplicantFocusYesClosedAwardDirectGrant=Automation IND By Applicant Admin Closed Award
AdminByApplicantFocusNoClosedAwardDirectGrant=Automation By Applicant Focus No Admin Closed Award
INDAdminByApplicantFocusNoClosedAwardDirectGrant=Automation Ind By Applicant Focus No Admin Closed Award
ClosedAwardByAppDetailBudget=Automation Closed Award By App Details Budget Yes
ClosedIndAwardByAppDetailBudget=Automation Ind Closed Award By App Details Budget Yes
AdminByApplicantFocusAreaClosedAwardDirectGrant=Automation By Applicant Focus Area Admin Closed Award
StringOf100Chars=test1234567890095test123678912q3rt45y167y452h4y18k38sgqq116637sdget3467qwysgh3467iujfgvbfhtyyy345677
StringOf60Chars=test1234567890095test123678912test1234567890095test123678912
StringOf55Chars=test1234567890095test123678912test1234567890095test1236
StringOf35Chars=test1234567890095test123678912ut123
StringOf30Chars=test1234567890095test123678912
CompetitiveClosedAnnDetailBudgetYes=Automation Runtime Competitive Announcement2835063568
CompetitiveClosedAnnoucement=Automation Runtime Competitive Announcement620785520