strategicGoalObjectivesTableId=GrantorStrategicGoalObjectives
strategicGoalRelatedObjectivesTableId=RelatedObjectivesGrantor
ObjectivesKPITableId=KPIGoalsandObjectivesGrid
ListOfActiveKPITableId=SelectKPIs
StrategicPlansTableId=StrategicPlansGrantor
StrategicPlanFilesTableId=StrategicPlanFiles
flexGridGrantorStrategicGoalFiles=GrantorStrategicGoalFiles
flexGridGrantorObjectiveFiles=GrantorObjectiveFiles
strategicGoalObjectivesAttTableId=GrantorStrategicPlanFiles
ActiveGrantsTableIdStrategicPlanTableId=StrategicPlanRelatedAwards