termsandconditionstableID=MasterTermConditions
formsflextableID=AllformsGrid
externalProgramTableID=FederalPrograms
paymentrequestAdvancesTableId=GrantorPaymentRequestAdvances
paymentrequestReimbursementTableId=GrantorPaymentRequestReimbursement
scheduledactivtiesTableId=MonitoringScheduleGrantor
subrecipientOrgTableId=ActiveAccount
orgRiskAssessmentTableId=flexGridOrganizationRiskAssessmentFlexGrid
deskreviewTableId=DeskReview
siteVisitTableId=SiteVisit
amendmentRequestTableId=GrantorAmendmentRequests
packagesFlextableID=FormsandPackages
federalProgramFlexTableId=FederalPrograms
applicationTableId=ApplicantGrantorApplications
#applicationTableId=AppReviewList
fundingSourceExternalTableId=ExternalFundingSource
#nonfederaltableId=NGOPrograms
nonfederaltableId=NGOProgramsForGranator
monitoringtableid=RiskAssessmentGridViewInternal
deskreviewMonitoringTableId=LatestDeskReviewReportsGrid
progressreportTableId=GrantorProgressReportsInternal
sitevisitMonitoringTableId=SiteVisitsGridView
PreApplicationTableId=ExternalPreApplicationFilesgrid
