###################Home-Phase-side-subheader#########################

##########Contacts##############
ContactSubheaderName=Contacts
ExternalContact=External
InternalContact=Internal

#########Organization###########
OrganizationSubheaderName=Organizations
ExternalOrganization=External
InternalOrganization=Internal

###################Planning-Phase-side-subheader#########################
#########Setup##################
SetUpSubheaderName=Setup
StrategicPlanLinkName=Strategic Plans
ProjectsLinkName=Focus Areas
KPILinkName=Key Performance Indicators (KPI)

#########programs###############
ProgramsSubheaderName=Programs
ExternalPrograms=External
InternalPrograms=Internal

###################Opportunity-Phase-side-subheader#########################
#########Leads##################
LeadsSubheaderName=Leads
NotyetQualifiedLead=Not Yet Qualified
QualifiedLead=Qualified

#########Opportunities##################
OpportunitiesSubheaderName=Opportunities
NotConvertedOpportunityLinkName=Not Converted
ConvertedApplicationLinkName=Converted to Application

###################Application-Phase-side-subheader#########################
#########Application##################
ApplicationSubheaderName=Applications
PreApplicationLinkName=Pre-Applications
ApplicationLinkName=Applications

###################Grants-Phase-side-subheader#########################
#########Grants##################
GrantsAwardsAmendmentSubheaderName=Grants, Awards & Amendment Requests
GrantsLinkName=Grants
AwardsBudgetPeriodLinkName=Awards (Budget Periods)
AmendmentRequestLinkName=Amendment Requests

###################Monitoring-Phase-side-subheader#########################
#########Monitoring##################
MonitoringSubHeaderName=Monitoring
SchedulesLinkName=Schedules
ProgressReportsLinkName=Progress Reports
FinancialReportsLinkName=Financial Reports

###################Closeout-Phase-side-subheader#########################
#########Closeout##################
BudgetPeriodCloseoutLinkName=Budget Period Closeouts
ProjectPeriodCloseoutLinkName=Project Period Closeouts
CloseoutSubheaderName=Closeouts

