###################Home-Phase-side-subheader#########################

##########Home##############
MyTasksLinkName=My Tasks
PendingTaskLink=Pending Tasks
CompletedTaskLink=Completed Tasks
ReassignLink=Reassign
##########Contacts##############
ContactSubheaderName=Contacts
smeReviewer=SME Reviewers
SubrecipientsLink=Subrecipients
InternalLink=Internal
SMEReviewersLink=SME Reviewers
#########Activities############
ActivitiesSubHeaderName=Organization
PendingSubrecipient=Pending Subrecipient Registrations