organizationId=Organizations
internalOrganizationId=InternalOrganizationHierarchyEnhanced
dunsTableId=GrantoeRelatedDUNS
relatedContactsTableId=GrantorRelatedContacts
additionalAddressTableId=GrantorAdditionalAddressInternal
reviewersTableId=Reviewers
internalContactTableId=InternalContacts
subrecipientActiveAccountId=ActiveAccount
termsAndConditionsTableId=MasterTermConditions
iFrameId=iframeFlexGridSearch
indContactTableId=AdditionalUser
indActiveAccountId=ActiveAccountIndApplicant
contactsTableId=DataTableEnhanceProgramContacts
associateContactsTableId=AssociateProgramContacts
externalPendingTasktableId=PendingTasks
completedAssignedToMe=HomePhaseCompletedTasks
completedAssignedByMe= HomePhaseCompletedTasksBy
internalHomePendingTaskTableId=HomePendingTasks
#indirectRateFlextableId=inlineEditGridGrantorIndirectRateGrid
indirectRateFlextableId=GrantorIndirectRateGrid
subrecipientcontactTableId=flexTableRandomID
planningPendingTaskTableId=PhasePendingTasks
userContactsTableId=AdditionalUser
SubmittedApplicationTableId=RecipientAppReviewList
RelatedLogGrantsTableId=ActiveGrantsByOrganization
focusAreaFilesTableId=GrantorFocusAreaFilesiframeContentId
subrecipientContactTableId=SubrecipientContacts
internalOrganizationAddfile=InternalOrganizationFiles
OrganizationAddfile=OrganizationFiles
InternalOrgHierarchyTableID=InternalOrganizationHierarchyEnhanced
