checklistTableId=ProgramChecklists
contactsTableId=DataTableEnhanceProgramContacts
associateContactsTableId=AssociateProgramContacts
extapproverTableId=ProgramRolesAndResponsibilities
#approverTableId=ProgramRolesAndResponsibilitiesgrid
approverTableId=ProgramRolesAndResponsibilitiesInternalProg
focusAreaTableId=GrantorServiceAreasProgram
associateFocusAreaTableId=SelectProgramServiceArea
#objectivesTableId=RelatedProgramGoalsandObjectives
objectivesTableId=RelatedProgramGoalsandObjectives
associateObjectivesTableId=SelectGoals
kpiTableId=ProgramKeyOutcomes
associateKPITableId=SelectProgramKPIs
pendingTaskTableId=PhasePendingTasks
programsTableId=Programs
peerReviewTableId=ProgramReviewerEnhancedGrid
reviewStepTableId=ProgramReviewStepTemplates
reviewFormTableId=ProgramReviewStepPanelTemplatesmodalDiv
programReviewPanel=ProgramReviewPanelCategories
programReviewPanelQuestionsTableId=ProgramRelatedReviewPanelQuestions
ProgramBusinessFormTableId=ProramPackagesGrantor
reviewFormPanelId=ProgramReviewStepPanelTemplates
GrantorInternalProgramFilesTableId=GrantorInternalProgramFiles
ProgramFundingAccountTableId=FundingAccountsEnhancedGrid
AnnouncementTableId=RelatedAnnouncements
ExternalNGOProgramTableId=NGOProgramsForGranator
ExternalNGOProgramContactTableId=ProgramContacts
businessFormTableId=ProramPackagesGrantor
previewPackageTableId=PreviewPackageForms
packagesTableId=FormsandPackages
programOwnerTableId=ProgramOwnerResponsibilities
grantorTaskReassignTableId=TaskReassignment
homePendingTableId=HomePendingTasks
adminTaskReassignmentTableId=TaskReassignment
adminOwnerReplaceTableId=ProgramSourceOwnerReplace
adminTargetOwnerReplaceTableId=ProgramTargetOwnerReplace
internalProgramNotesTableId=InternalProgramContentNotes
historyTableId=History
completedTaskTableId=PhaseCompletedTasks
supportDocIframeId=ProgramChecklistsiframeContentId
addFilesIframeId=GrantorInternalProgramFilesiframeContentId
packagesFormsTableId=AssociatedFormsGrid
formsPackagesFormsTableId=AllformsGrid
snapshotHistoryTableId=a0t4T000000YQVFQA4
addReviewersTableId=ProgramRelatedReviewStepUsers
programCollabMessagesTableId=CommunicationHistory
systemEmailsTableId=RecordSystemEmailHistory
externalProgramNotesTableId=ExternalProgramContentNotes
externalProgramAddFilesYableId=ProgramFiles