#paymentRequestSchedulesTableId=flexGridPaymentSchedules
paymentRequestSchedulesTableId=PaymentSchedules
progressReportSchedulesTableId=TnCSchedules
approversTableId=GrantorAwardRolesAndResponsibilities
subawardsTableId=RelatedAwards1
associateContactTableId=SubawardContact
keyContactsTableId=AssociateSubawardContacts
AwardFundingAccountsgrid=AwardFundingAccounts
awardFundingAccountsTableId=SelectAwardFundingAccounts
AwardFundingAccountTableId=AwardFundingAccounts
focusAreaTableId=EnhancedGrantorAwardServiceAreas
subAwardBudgetTableId=SubAwardBudgetCategoryFlexGrid
objectivesTableId=GrantorAwardGoalsObjectives
kpiTableId=GrantorAwardKeyOutcomes
peerReviewersTableId=GrantorAwardReviewer
announcemetTableId=ActiveFundingOpportunitiesCompitive
recommendedAppTableId=FundingDecisionMemoApplications
fdmTableId=FDMList1
pendingTaskTableId=PhasePendingTasks
awardApproverTableId=GrantorAwardRolesAndResponsibilities
riskAssessmentTableId=AwardRiskAssessmentView
riskAssessmentApproverTableId=GrantorRiskAssessmentRolesandResponsibilities
#grantsTableId=ActiveGrants
grantsTableId=GrantorActiveGrants
grantPackagesTableId=GrantPackages
federalProgramTableId=RelatedFederalProgramForAward
federalListTableId=SelectAwardCFDA
PhasePendingTasksByTableId=PhasePendingTasksBy
relatedloggrant=AnnouncementActiveGrants
relatedLogFederalGrant=GranteeGrantsByAccount
GrantsRolesAndResponsibilitiesTableId=GrantorAwardRolesAndResponsibilities
RecipientGrantsTableId=RecipientActiveGrants
RecipientGrantsTableIdSPA=RecipientActiveGrants
RecipientSubAwardTableId=RecipientsRelatedAwards1
RecipientGrantsPendingTableId=GrantsList
SubAwardBudgetTableId=SubAwardBudgetCategoryFlexGrid
fdmNonRecommendedTableId=FundingDecisionMemoNonRecommendApplication
fdmApproverTableId=GrantorReviewStepRolesandResponsibilities
subrecipientPendingTaskTableId=PhasePendingTasks
GrantorAwardNotesTableId=GrantorAwardNotes