#######################Forms And Package##########################
GrantorPackagesTableId=FormsandPackagesgrid
PackageAssociateFormsTableId=AssociatedFormsGridgrid
PackageAddFormsTableId=SelectForms

#######################Terms and condition##########################
GrantorTermsAndConditionTableId=MasterTermConditions

#######################Planning#########################
ProgramPeerReviewTableId=ProgramReviewerEnhancedGridgrid