fullName=Automation IND
OldfullName=AutomationInd ind123
orgRegistrationAttachmentTableId=UserRegistrationAttachment
communityPopulationExternal=CommunityPopulationExternal
communityPopulationExternalAdd=CommunityPopulationExternalAdd
NewUser=Will Turner
InvitationSentUser=Peter San
ActiveUser=jonny math
InactiveUser=Robt Ashley