reviewsTableId=NotYetQualifiedAnnouncementsExternal
budgetTableId=EnhanceAppBudCatGrantorFlexGrid
kpiTableId=RecipientApplicationRelatedKPIs
allFormsTableId=FormEnhancedTableFlexGrid
announcementTableId=AnnouncementList
reviewStepsTableId=AnnouncementReviewSteps
formTableId=ApplicationReviewTree
reviewersTableId=ReviewStepUsers
assignApplicationsTableId=AssignAppToUser
applicationAssignTableId=PreScreenRelatedStepApplicationsFinal
rejectedApplicationTableId=FundingDecisionMemoRejectedApplications
appreviewsTableId=StepReviews
pendingTaskTableId=PhasePendingTasks
appTableId=PreScreenRelatedStepApplicationsFinal
panelAppTableId=AssignPanelApplications
reviewFormsTableId=RelatedPanelApplicationsGrid
budgetPeriodTableId=EnhanceAppBudCatGrantorFlexGrid
announcementListTableId=AnnouncementList
flexGridAppContactTableId=AppContactFlexGrid
relatedFOApplicationsTableId=RelatedFOApplications
reviewStepFormId=ApplicationReviewTree
reviewPanelCategoriesTableId=ReviewPanelCategories
completedTaskTableId=HomePhaseCompletedTasks
PhaseRespectivecompletedTaskTableId=PhaseCompletedTasks
qaOrgAppFormTableId=FormEnhancedTableFlexGrid
fdmOwnerTableId=GrantorFDMOwnerRoles
reSubmittedAppTableId=ResubmittedStepApplications
grantorApplicationFilesTableId=GrantorApplicationFiles
recommendedTableId=FundingDecisionMemoApplications
nonRecommendedTableId=FundingDecisionMemoNonRecommendApplication
addLineItemsModalTableId=AppLineItems
subrecipientApplicationReviewTableId=PendingReviews
FDM_FA_TableID=FDMFundingAccountGrantor
FDM_FA_AssociateModalID=SelectAnnFundingAccounts



