focusAreaTableId=FocusAreaApp
budgetPeriodTableId=EnhanceAppBudCatGrantorFlexGrid
kpiTableId=RecipientApplicationRelatedKPIs
allFormsTableId=FormEnhancedTableFlexGrid
attachmentsTableId=inlineEditGridApplicationChecklists
activeOpportunitiesTableId=NotYetQualifiedAnnouncementsExternal
recipientPreApplicationsTableId=RecipientPreApplications
appAllTableId=ApplicantGrantorApplications
applicantGrantorApplicationsTableId=ApplicantGrantorApplications
#qualifiedTableId=flexTableDivId
qualifiedTableId=QualifiedAnnouncementsExternal
NotYetQualifiedTableId=NotYetQualifiedAnnouncementsExternal
goalsAndObjectivesTableId=GoalsQualifiedApplicationsFlexGrid
associateNewContactsTableId=AssociateAppContacts
publishedOpputunityTableId=AnnouncementsExternalActive
recipientApplications=RecipientApplications
#recipientApplications=ApplicantGrantorApplications
convertedToApplicationTableID=ConvertedAnnouncementsExternal
formulaAllocatedAmountTableId=SoleSourceAwardForRecipient
focusAreaFlexTableId=RemoveAppProjects
focusAreaTableAppId=FocusAreaPreApp
AddFocusAreaTableAppId=AddAppProjects
RemoveFocusAreaPreAppTableId=RemovePreAppProjects
focusAreaAssociateTableId=AddPreAppProjects
#applicationContactsTableId=flexGridAppContact
applicationContactsTableId=AppContactFlexGrid
applicationAssociateTableId=AssociateAppContacts
#ApplicationAttachmentTableId=ApplicationChecklistsgrid
ApplicationAttachmentTableId=ExernalApplicationFiles
ApplicationNotesTableId=SubrecipientApplicationContentNotes
supportedDocumentsTableId=ApplicationChecklists
appContactsTableId=EnhancedDivId
budgetSummaryTableId=ByApplicantBudgetSummary
budgetSumamaryByFocusAreaTableId=FocusAreaAppFlexGrid
grantorApplicationNotesTableId=GrantorApplicationContentNotesFlexGrid
subrecipientApplicationNotesTableId=SubrecipientApplicationContentNotes
applicationPhaseTableId=AppReviewList
fundingOppurtunityTableId=applicationIntake
SubRecipientBudgetPeriodTableId=EnhanceAppBudCateGrantorFlexTable
applicationTitle=Title__c
LineItemDetailsDetailTableID=ProfessionalSalariesLineItems
IndirectCostLineItemDetailsDetailTableID=IndirectCostLineItems
PurchasedServicesCategoryTableId=PurchasedServicesLineItems
SupportStaffSalariesCategoryTableId=SupportStaffSalariesLineItems
SuppliesAndMaterialsCategoryTableId=SuppliesAndMaterialsLineItems
TravelExpensesCategoryTableId=TravelExpensesLineItems
EmployeeBenefitsCategoryTableId=EmployeeBenefitsLineItems
BOCESPurchasedServicesCategoryTableId=BOCESPurchasedServicesLineItems
MinorRemodelingCategoryTableId=MinorRemodelingLineItems
EquipmentCategoryTableId=EquipmentLineItems
SupportingDocumentsChecklistTableId=ApplicationChbudgetTableIdecklistsFlexGrid
ExternalSupportingDocumentsChecklistTableId=ApplicationChecklistsFlexGrid
FocusAreasTableId=AnnouncementServiceArea1
SubreceipentFocusAreasTableId=RecipientAnnouncementServiceArea1
ApplicationReviewsTableId=AnnouncementList