subawardBudgetTableId=SubAwardBudgetCategoryFlexGrid
EquipmentCategoryTableId=AwardEquipmentLineItems
EmployeeBenefitsCategoryTableId=AwardEmployeeBenefitsLineItems
SupportStaffSalariesCategoryTableId=AwardSupportStaffSalariesLineItems
