##########ContactsTableId######################
ExternalFederalContacts=FederalContactsEnhancedGridgrid
ExternalNonFederalContacts=NGOContactsEnhancedGridgrid
InternalContacts=StateContacts
RelatedContacts=GranteeContactsByInternalAccount
FedOrgRelatedContacts=GranteeContactsByAccountNew
relatedLogActiveLeads=LeadsonFedAgency
relatedOpportunity=AnnouncementsByAccount
relatedLogApplications=FederalAgencyApplications
relatedLogGrants=AgencyRelatedAwards
federalFilesTableId=Non-FederalFiles
fedNotesTableId=NonFederalNotes
childOrganizationTableId=GranteeChildOrganizations
indirectRateTableId=IndirectRateGrid
uieNumberTableId=RelatedDUNS
fedContactTableId=FederalContacts
##########OrganizationsTableId######################
NonFederalOrganizations=NGO_OrganizationEnhacedGridgrid
InternalOrganizations=InternalOrganizationHierarchyEnhanced
FederalOrganizations=FederalOrganizationEnhacedGridgrid
relatedLogsQualifiedLeadsTableId=AgencyQualifiedLeadsRelated
internalOrgFilesTableId=InternalOrgFiles
internalOrgNotesTableId=InternalOrgNotes
nonFedChildOrgTableId=GranteeChildOrganizationsNonFederal

##########ProgramTable######################
InternalProgram=AgencyProgramsgrid
NonFederalPrograms=EnhanceNGOProgramEnhancedGridgrid
StrategicPlans=EnhanceStrategicPlanHierarchy
strategicPlansFilesTableId=StrategicPlanFiles
strategicPlansNotesTableId=StrategicplanNotes
strategicPlanKPITableId=KPIOnStrategicPlan
StrategicGoalsandObjective=EnhanceStrategicGoalObjectives
strategicGoalsFilesTableId=StrategicGoalFiles
strategicGoalsNotesTableId=StrategicgoalNotes
StrategicObjectivesChild=StrategicObjectivesChild
StrategicGoalsChild=StrategicGoalsChild
Objectives=EnhanceRelatedObjectives
strategicObjectivesKPITableId=KPIGoalsandObjectivesGrid
objectivesSelectKPITableId=SelectKPIs
objectivesAddFilesTableId=ObjectiveFiles
objectivesNotesTableId=ObjectiveNotes
Projects=GranteeServiceAreasFlexToggle
ProjectsFieldHistory=flexTableDivId
InternalProgramsListPage=EnhanceGranteeStateProgramsgrid
ExternalFederalPrograms=FederalPrograms
GranteeProjectTableId=EnhanceGranteeServiceAreas
focusAreaAddFilesTableId=FocusAreaFiles
focusAreaNotesTableId=FocusareaNotes
nonFederalProgramsTableId=NGOPrograms
nonFedAddFilesTableId=ProgramFiles
nonFedNotesTableId=NonFederalProgramNotes

##########LeadsTable########################
OpenQualifiedTable=StateAgencyFundingOpportunitiesgrid
LeadsNotYetQualified=Leads
QualifiedLeads=QualifiedLeadsGridgrid
RelatedPrograms=RelatedLeadCFDANumbers
AllQualificationsTable=RelatedQualifiedLeads
AllQualificationsAfterQualifiedLead=LeadQualificationDetails
OrganizationModal=lookuploading
AssociateExternalProgram=SelectFOALeadCFDA
LeadsAttachmentTableId=ManualLeadNotes
preApplicaltionTableId=OpenGranteePreApplications
preApplicationExternalProgramTableId=RelatedPreApplicationCFDANumbers
preAppAssociateProgramTableId=SelectPreAppCFDA
preApplicationContactTableId=GranteePreAppContact
preAppAssociateContactTableId=AssociatePreApplicationContacts
preResponsibiltiesTableId=GranteePreApplicationRolesandResponsibility
preApplicationOwnerTableId=GranteePreApplicationOwner
preApplicationAddFilesTableId=PreApplicationFiles
preApplicationNotesTableId=GranteePreappLwcNotes
leadsAddFileTableId=LeadFiles
qualifiedLeadTableId=AgencyQualifiedLeads
qualifiedLeadsAddFileTableId=QualifiedLeadFiles
qualifiedLeadsNotesTableId=QualifiedLeadNotes
opportunityExternalProgramTableId=RelatedAnnouncementCFDANumbers
opportunityExternalProgramModalTableId=SelectAnnCFDA
opportunityApproverTableId=GranteeOpportunityRolesandResponsibility

##########OpportunityTable########################
OpportunityPeerReviewers=ApproverRoles

Approvers=AnnouncementRolesandResponsibilitiesFlexToggle
Opportunities=OpportunitysGrantee
OpenOpportunity=StateAgencyFundingOpportunitiesgrid
OpportunityNotConvertedToApplication=AnnouncementsGrantee
OpportunityConvertedToApplicationTableId=ExpiredFundingOpportunities
OpportunityConvertedToApplication=EnhanceGranteeServiceAreasgrid
PendingTask=PendingTasksAssignedtoMe
PhasePendingTask=PhasePendingTasks
HomePendingTask=HomePendingTasks
OpportunityNotConvertedAdvanceFilterId=advfAnnouncementsGrantee
OpportunityConvertedToApplicationAdvanceFilterId=advfExpiredFundingOpportunities
HomeCompletedTask=HomePhaseCompletedTasks

##########Pre-Applications########################
PreApplication=OpenGranteePreApplications
PreAppOverview=flexGridDivId
BudgetPeriodDetails=ApplicationBudgetSetupGridgrid
BudgetPeriodDetailsFromBudgetTab=PreAppGranteeServiceArea
ChildBudgetPeriodDetailsFromBudgetTab=PreAppGranteeServiceAreaFlexToggle
AssociateProjects=toggleFlexTablepopupflextable
PreApplicationPeerReviewers=GranteePreApplicationApproverRoles
ApplicationTableId=ManageApplications
AssociateProjectsModal=popupflextable1
AssociateProjectModal2=popupflextable2
AssociateFocusAreaModalTableId=ModalDivID
SelectBudgetPeriodsAdvanceFilter=advfpopupflextable1
IndirectRateModal=lookuploading
BudgetLevelWithLineItem=PreApplicationBudgetPeriodsFlexToggle
BudgetCategorySearch=PreApplicationBudgetCategoryFlexTableFlexToggle
AddLineItemBudgetModal=inlineEditGridPreAppLineItem
PreApplicationApprovers=GranteeAnnouncementRolesandResponsibilitygrid
PreApplicationBudgetPeriodDetails=PreApplicationBudgetSetupGrid
FieldHistoryForPreApplication=toggleFlexTableHistory
ApplicationContactTableId=GranteePreAppContactgrid
ContactTableIdApplication=GranteeAppContact
ContactModalTableIdApplication=GranteeAssociateAppContacts
BudgetPeriodDetailsTableIdApplication=flexGridApplicationBudgetSetupGrid
ApplicationContactModalTableId=AssociatePreApplicationContacts
PreApplicationAssociateBP=SelectBudgetPeriod1
PreApplicationAssociateFocusArea=SelectPreappGAT
PreApplicationBudgetCategoryTableId=PreApplicationBudgetCategoryFlexTable
PreApplicationDetailsLineItemTableId=PreAppLineItemsGrantee
ApplicationBudgetPeriodModalTableId=SelectBudgetPeriod
ApplicationSelectFocusAreaModalTableId=SelectGAT
ApplicationBudgetCategoryTableId=ApplicationBudgetCategoryFlexTable
ApplicationDetailsLineItemTableId=AppLineItemsGrantee

##########Applications########################
Application=ManageApplications
ApplicationOverview=inlineEditGridRelatedApplicationCFDANumbers
ApplicationSetup=ApplicationBudgetSetupGridgrid
ApplicationPeerReview=GranteeApplicationReviewer
BudgetPeriodDetailsFromSetup=ApplicationBudgetSetupGrid
LineItemBudgetLevel=ApplicationBudgetPeriodsFlexToggle
ApplicationApprovers=GranteeApplicationApprovers
SummaryBudgetLevel=inlineEditGridApplicationServiceAreaFlexGrid
#ApprovalHistory=approvalHistoryComponent
ApprovalHistory=toggleFlexTableHistory
FieldHistory=toggleFlexTableHistory
BudgetPeriodDetailsFromBudget=inlineEditGridApplicationServiceAreaFlexGrid
BudgetCategoryForLineItemBudget=ApplicationBudgetCategoryFlexTableFlexToggle
AddDetailedLineItemBudgetModal=ApplicationBudgetCategoryFlexTableiframeContentId
ApplicationBudgetDetailsTableId=ApplicationBudgetCategoryFlexGridgrid
ChildBudgetPeriodDetailsFromBudgetOfSetUp=ApplicationGranteeServiceArea
ApplicationExternalProgramsTableId=RelatedApplicationCFDANumbersgrid
applicationBusinessFormTableId=ApplicationEnhamcedGranteeForm
applicationFormAddFileTableId=FormFiles
##########Monitoring########################
ScheduledListPage=GranteeMonitoringSchedule
FinancialReportsOnAwards=RelatedGranteeFinancialReportsOnAward
FinancialReportsOnMonitoring=GranteeFinancialReports
monitoringTabSchedulesTableId=MonitoringScheduleGrantor
Forms=FormComponent
OtherKeyContactsForFinancialReport=ProgressReportContacts
progressReportApprovers=GranteeProgressReportApprovers
ProgressReports=GranteeProgressReports
KPIOnProgressReport=ProgressReportKeyOutcomes
ObjectivesFromProgressReport=ProgressReportObjectivesGridgrid
financialReportPeerReviewTableId=GranteeProgressReportReviewer
financialReportApproverTableId=GranteeFinancialReportApprovers
monitoringCompletedTaskTableId=PhaseCompletedTasks
financialReportOwnerTableId=GranteeProgressReportsOwnerRoles
financialReportFormsTableId=PRFRGranteeForm
financialReportFormFilesTableId=FederalFinancialReportFormFiles
financialReportAddFilesTableId=FinancialReportFiles
financialReportNotesTableId=ProgressReportNotes
financialReportProgressReportSchedules=GranteeRelatedSchedules
progressReportObjectivesTableId=StrategicGoalsPRFR
progressReportFileTableId=ProgressReportFiles
specialConditionPhaseLevelTableId=AwardTermsandConditions
specialConditionsChildTableId=GranteeMonitoringTermsandConditionsChild
##########Kpi########################
#KPITable=flexGridEnhanceMasterKPIsGrid
KPITable=EnhanceMasterKPIsGrid
KPIFilesTableId=KPIFiles
KPINotesTableId=KPINotes
KPIObjectivesTableId=Goals
PlanningAssociateObjectiveTableId=flexGridGoals
PlanningObjectiveModalTableId=GoalsiframeContentId
##########Grants&AwardsTable########################
GrantsTable=GranteeGrants
GrantsLevelDetailsTableId=GrantLevelDetailsgrid
AwardsTable=GranteeActiveAwardsgrid
OtherKeyContactsTableId=AwardContacts
AwardProgressReportSchedule=TnCSchedulesgrid
ProjectTableId=AwardServiceAreas
selectAwardFocusAreaTableId=SelectGATforAward
AwardBudgetTableId=AwardBudgetCategoryFlexGrid
awardProgramIncomeTableId=AwardProgramIncome
awardLineItemsTableId=AwardLineItemsGrantee
awardPeerReviewerTableId=GranteeAwardReviewer
awardIndirectRateTableId=AwardIndirectRateFlex
ExpenditureDetailsTableId=AwardBudgetCategoryExpensesFlexGrid
ProgressReportTableId=RelatedGranteeProgressReportsOnAward
FinancialsReportTableId=RelatedGranteeFinancialReportsOnAward
KeyPerformanceIndicatorTableId=AwardKeyOutcomes
ObjectiveTableId=GranteeObjectivesNewgrid
SpecialConditionTableId=GranteeTermsandConditions
AmendmentsTableId=GranteeAmendmentRequest
awardApproverTableId=GranteeAwardApprovers
awardObjectiveTableId=StrategicGoalsObjectivesHierarchyAward
selectAwardKPITableId=SelectAwardKPIs
awardAssociateObjectiveTableId=SelectAwardGoals
awardAddFilesTableId=AwardGrantFiles
awardsNotesTableId=AwardNotes
awardReportSchedulesTableId=GranteeProgressReportSchedules
awardCloseoutTableId=GranteeBudetPeriodCR
GrantRelatedApplicationTableId=GrantViewrelatedapplicationgrid
AwardRelatedApplicationTableId=GranteAwardrelatedapplicationgrid
GrantRelatedFundingProgramsTableId=RelatedAwardGrantCFDANumbersgrid
GrantsKeyContactTableId=GrantContacts
GrantsAwardsRevisionTableId=GranteeRelatedAwards
GrantsBudgetTableId=AwardsBudgetCategoriesNVGridgrid
GrantsFinancialsByPrpjectTableId=AwardsListFromGrantFlexToggle
GrantsAmendmentRequestsTableId=AmendmentRequestReport
GrantsPerformanceProgressReportTableId=GrantKeyOutcomesgrid
GrantsFinancialReportTableId=RelatedGranteeFinancialReportsOnGrant
GrantsObjectiveTableId=GrantStrategicGoalsObjectives
GrantsSpecialConditionTableId=GranteeGrantTermsandConditions
GrantsProjectPeriodCloseoutTableId=GranteeCompletedCloseOutRequest
grantFocusAreaTableId=GrantFocusAreas
grantContactTableId=GranteeGrantContact
grantExternalProgramTableId=RelatedAwardCFDANumbersG
grantBudgetCategory=GrantBudgetCategoryGrantee
AwardKPITableId=popupflextable
AwardReportPreparerTableId=GranteeAwardReportPreperargrid
ProgressReportsSchedule=RelatedPRSchedulesFlexToggle
DrawdownTableId=AwardBudgetCategoryDDFlexGrid
GrantDrawDownTableId=AwardDrawdownsGridgrid
AwardExpendituresDetails=toggleFlexTableRifanExpensesFlex
AwardActualsModalExpenditureTableId=RifanExpensesFlex
AwardActualsModalCashMatchTableId=RifanExpensesStateFlex
AwardActualsModalProgramIncomeTableId=RifanPIExpensesFlex
AwardActualsMoalNonCashMatchTableId=LineItemNonCash
CashMatchExpendituresDetails=toggleFlexTableRifanExpensesStateFlex
fedOrgTableId=ExternalOrganizationHierarchy
nonFedOrgTableId=NGOOrganizationHierarchy2
awardContactTableId=GranteeSubawardContact
awardAssociateContactTableId=AssociateSubawardContacts
awardExternalProgranTableId=RelatedAwardCFDANumbers
awardAssociateExternalProgranTableId=SelectCFDA
nonFedContactTableId=NGOContacts
amendmentObjectiveTableId=GranteeAmendmentGoalsObjectives
amendmentAssociateObjectiveTableId=SelectAmendmentGoals
grantCompletedTaskTableId=PhaseCompletedTasks
awardProgramRevenueTableId=AwardBudgetCategoryPIFlexGrid
grantBudgetCategoryTableId=GrantBudgetCategoryFlexGridGrantee
grantAddFilesTableId=GrantFiles
grantNotesTableId=GrantNotes
grantProgressReportTableId=GranteeGrantProgressReport
grantGoalsTableId=GrantStrategicGoalsObjectivesEnhance
grantKPITableId=GrantKeyOutcomes1
actualsTabProgramIncomeTableId=AwardBudgetCategoryPIFlexGrid
actualsTabDrawDownTableId=AwardBudgetCategoryDDFlexGrid
peerReviewChildTableId=GranteeAmendmentReviews


###################CloseoutTable##############
AwardbudgetperiodcloseoutTableId=PendingCloseoutRequestGridgrid
BudgetPeriodListPageTableId=flexGridBudgetPeriodCloseOutRequestEnhancedGrid
BudgetPeriodCloseoutListTableId=BudgetPeriodCloseOutRequestEnhancedGridgrid
ProjectPeriodCloseoutListTableId=ProjectPeriodCloseOutRequestEnhancedGridgrid
CloseoutApproversTable=GranteeCloseoutApproversgrid
ProjectPeriodCloseout=ProjectPeriodCloseOutRequestEnhancedGridgrid
PendingProgressReprt=GrantGranteeProgressReports
PendingFinancialReport=GrantGranteeFinancialReports
PendingProgressReportForBudgetPeriod=PendingProgressReportsgrid
PendingFinancialReportForBudgetPeriod=PendingFinancialReportsgrid
BudgetPeriodCloseoutAdvanceSearch=advfBudgetPeriodCloseOutRequest
pendingAmendmentCloseoutTableId=GrantCloseOutAmendmentRequest
closeoutPeerReviewTableId=GranteeCloseoutPeerReview
closeoutApproverTableId=GranteeCloseoutRequestRolesAndResponsibilities
closeoutAddFilesTableId=CloseoutViewFiles
closeoutNotesTableId=CloseoutNotes
phaseCloseoutTableId=GranteePhaseCloseOutRequest


##########AmendmentTable########################
AmendmentRequestTableId=GranteeAmendmentRequest
AmendmentKeyPerformanceIndicatorTableId=AmendmentKeyOutcomesgrid
AmendmentKPIAssociationmodalTableId=popupflextable
AmendmentObjectiveTableId=AmendmentObjective
AmendmentObjectiveAssociationmodalTableId=popupflextable
AmendmentKeyContactsTableId=AmendmentContactgrid
AmendmentSpecialConditionTableId=GranteeTermsandConditionsAmendmentgrid
AmendmentApproverRolesTableId=AmendmentRequestApprovalRolesGranteeNew
amendmentLineItemsTableId=AmendmentLineItemGranteeTable
AmendmentBudgetTableId=GanteeAmendmentRequestBudgetGrid
AmendmentTableId=GranteeAmendmentRequests
amendmentFocusAreaTableId=AmendmentProjectAreas
amendmentIndirectRateTableId=AmendmentIndirectRate
amendmentSpecialConditionsTableId=GranteeSpecialConditionsAmendment
amendmentPeerReviewerTableId=GranteeAmendmentPeerReview
amendmentRequestAddFile=AmendmentRequestFiles
amendmentRequestNotesTableId=AmendmentRequestNotes
amendmentMessageTableID=CommunicationHistory
selectAmendmentFocusAreaTableId=SelectAmendmentGAT
amendmentContactTableId=GranteeAmendmentKeyContact
amendmentAssociateContactTableId=AssociateAmendtmentContacts
grantBudgetPeriodDetailsTableId=GranteeBudgetPeriods
grantGrantBudgetTableId=GrantBudgetCategoryFlexGridGrantee
amendmentKPITableId=GranteeAmendmentKeyOutcomes
selectAmendmentKPITableId=SelectAmendmentKPIs
carryForwardBudgetTableId=GranteeAmdRequestCarryForwardBudget
##########Closeout######################
closeoutTableId=GranteePhaseCloseOutRequest

##########Awards##############################
awardTableId=GranteeActiveAwards
awardOwnerTableId=GranteeAwardOwnerRoles
grantFocusAreaTable=GrantFocusAreas
DrawdownByAwardModalTableId=RifanExpensesOtherFlex


###################################################
preAppcationBudgetTableId=PreApplicationBudgetSetupGrid
preAppAssociateBudgetTableId=SelectBudgetPeriod1
preAppAssociateFocusAreaTableId=SelectPreappGAT
preApplicationProgramIncomeTableId=PreAppProgramIncome
preApplicationIndirectRateTableId=PreApplicatonIndirectRate
preAppBudgetDetailTableId=PreApplicationBudgetCategoryFlexGrid
preApplicationFocusAreaTableId=PreAppGranteeServiceArea
preAppllicationLineItemsTableId=PreAppLineItemsGrantee
opportunitysGranteeTableId=OpportunitysGrantee
qaulifiedLeadsTableId=AgencyQualifiedLeads
preApplicationAddFileTableId=PreApplicationFiles
preApplicationNoteTableId=GranteePreappLwcNotes
preApplicationPeerReviewTableId=GranteePreApplicationApproverRoles
preApplicationApprovalTableId=GranteePreApplicationRolesandResponsibility
opportunityPeerReviewTableId=ApproverRoles
opportunityApprovalTableId=GranteeOpportunityRolesandResponsibility
fundingOpportunitiesTableId=ExpiredFundingOpportunities
applicationKeyContactFormTableId=KeyContacts
applicationProjectNarrativeAttachmentTableId=FormFiles










