phasePendingTasksTableId=PhasePendingTasks
homePendingTasks=PendingTasks
negotiationCompletedTaskTableId=CompletedNegotiations
negotiationAppReviewListTableId=ApplicantGrantorApplications
negotiationPendingTaskTableId=PendingNegotiations
RecipientTableId=RecipientNegotiations
NegotiationFormsTableId=FormsRevisionApplicationFlexGrid
filesFormsTableId=FormEnhancedTableFlexGrid
internalHomePendingTableId=HomePendingTasks
addNotesTableId=GrantorApplicationNotes
negotiationFilesFormTableId=FormEnhancedTableFlexGrid
