paymentRequestTableId=RecipientsAwardPaymentRequests
GrantPaymentRequestTableId=CompletedPaymentRequestScheduleReport
paymentRequestBudgetTableId=ReimbursementRequestEnhanced
paymentLineItemsTableId=PaymentLineItems
grantorPaymentRequestTableId=AwardPaymentRequest
fundingAccountTableId=PaymentFundingAccountsEnhanced
payapproversTableId=PaymentRequestRolesandResponsibilities
approversTableId=PaymentRequestRolesandResponsibilitiesAdvance
#grantorPaymentRequestApproverTableId=PaymentRequestRolesandResponsibilitiesgrid
ReimbursmentApproverTableId=PaymentRequestRolesandResponsibilities
#recipientGrantTableId=flexGridRecipientActiveGrants
recipientGrantTableId=RecipientActiveGrants
recipientAwardTableId=RecipientsRelatedAwards1
grantorAwardTableId=RelatedAwards1
advanceFundingAccountTableId=PaymentFundingAccountsAdvanceFlexToggle
#grantorGrantsTableId=ActiveGrants
grantorGrantsTableId=GrantorActiveGrants
pendingTaskTableId=PhasePendingTasks
subrecipientPendingTaskTableId=PhasePendingTasks
paymentRequestDisallowTableId=PaymentLineItemsDisallow
budgetTableId=AdvanceRequest
fundingAccountsAdvTableId=PaymentFundingAccountsAdvance
checklistTableId=PaymentRequestChecklists
completedTaskTableId=PhaseCompletedTasks
#recipientsSubawardTableId=flexGridRecipientsRelatedAwards2
recipientsSubawardTableId=RecipientsRelatedAwards2
ExternalAwardFilesTableId=ExternalAwardFiles
progressReportSchedulesTableId=TnCSchedules
recipientAdvancePaymentFilesTableId=RecipientAdvancePaymentRequestFiles
recipientReimbursmentPaymentFilesTableId=RecipientReimbursementFiles
recipientAdvanceSupportiveDocumentChecklistTableId=PaymentRequestChecklists
recipientPaymentRequestAttachmentModalIframeId=PaymentRequestChecklistsiframeContentId
PaymentRequestModalIframeId=PaymentRequestScheduleiframeContentId
paymentrequestAdvancesTableId=GrantorPaymentRequestAdvances
paymentrequestReimbursementTableId=GrantorPaymentRequestReimbursement
paymentRequestSourceOwnerTableId=PaymentRequestSourceOwnerReplace
paymentRequestTargetOwnerTableId=PaymentRequestTargetOwnerReplace
reimbursePaymentsNotesTableId=ReimbursementPaymentRequestContentNote
reimburseCollabMessages=CommunicationHistory
reimburseFilesTableId=GrantorReimbursementFiles
advanceFilesTableId=AdvancePaymentRequestFiles
addFilesTableIframeId=RecipeintAdvancePaymentRequestFilesiframeContentId
advancePaymentNotesTableId=AdvancePaymentRequestContentNote
reimbursementOwnerTableId=PaymentRequestOwnerRoles
reimbursementAddFilesTableId=RecipientReimbursementFilesiframeContentId
paymentRequestFormsTableId=FormEnhancedTablePaymetRequest
sf270ComputationAmountTableId=SF270PaymentRequestGrid
RecipientpaymentrequestReimbursementTableId=RecipientPaymentRequestReimbursement
subrecipientPaymentrequestAdvancesTableId=RecipientPaymentRequestAdvances
DocumentHistoryTableId=DocumentHistory
TransactionsTableId=Transactions_2025815104547
PRSupportStaffSalariesTableId=PRSupportStaffSalariesLineItems
PRIndirectCostLineItemsTableId=PRIndirectCostLineItems
PRSuppliesAndMaterialsLineItemsTableId=PRSuppliesAndMaterialsLineItems
PRProfessionalSalariesLineItemsTableId=PRProfessionalSalariesLineItems
PRTravelExpensesLineItemsTableId=PRTravelExpensesLineItems
PRBOCESPurchasedServicesLineItemsTableId=PRBOCESPurchasedServicesLineItems
PRPurchasedServicesLineItemsTableId=PRPurchasedServicesLineItems
SubreceipentPaymentRequestsTableId=RecipientAwardPaymentRequest
PaymentRequestsTableId=GrantorOrgnizationPaymentRequest
SnapshotHistoryTableId=SnapshotFiles
