participantsTableId=GrantorSiteVisitContacts
siteVisitContactsTableId=SelectSiteDeskReviewContacts
approverSiteVisitTableId=GrantorSiteVisitRolesandResponsibilities
correctiveTableId=GrantorSiteVisitFindingsGridRecipientEnhance
reportsTableId=SVDRFormEnhancedTable
receipientTableId=GrantorSiteVisitFindingsGridRecipientEnhance
manageSiteVisitTableId=LatestSiteVisitReportsGrid
monitoringTabPhasePendingTasks=PhasePendingTasks
awardSiteVisitsTableId=SelectAwardSiteDeskReviews
associateAwardSiteVisitsTableId=SiteVisitAssociatedAwards
grantHistoryTableId=toggleFlexTableHistory
#reviewersFlexTableId=flexGridSiteVisitReviewerRoles
reviewersFlexTableId=SiteVisitReviewerRoles
#homePendingTasksTableId=PhasePendingTasks
homePendingTasksTableId=HomePendingTasks
grantorSiteVisitsTableID=GrantorSiteVisitsAward
externalHomePendingTaskTableId=PendingTasks
siteVisitSupportingDocumentChecklist=SiteVisitGrantorChecklists
PendingSiteVisitDeskReviewTableId=SiteVisitsGrantorCloseoutGrid
grantsTableId=GrantorActiveGrants
InitiateSiteVisitTableId=GrantorSiteVisitsAward
GrantsSubAwardsTableId=RelatedAwards1
ApplicationInitiateSiteVisitTableId=GrantorSiteVisitsApplication
siteVisitSourceTableId=SiteVisitSourceOwnerReplace
siteVisitTargetTableId=SiteVisitTargetOwnerReplace
siteVisitOwnerTableId=GrantorSiteVisitOwnerRoles
siteVisitHistoryTableId=History
monitoringSiteVisitSubTableId=ApplicantSiteVisitReports
siteVisitAddFilesTableId=GrantorSiteVisitFiles
siteVisitNotesTableId=OrgSiteVisitContentNote
orgCorrectiveTableId=GrantorSiteVisitFindingsGrid
homeCompletedTaskTableId=HomePhaseCompletedTasks
snapshotHistoryTableId=toggleAttachmentsa0t4T000000YPsCQAW