subawardsTableId=RelatedAwards1
completeTaskTableId=PhaseCompletedTasks
associatedContactsTableId=SubawardContact
RecipientassociatedContactsTableId=RecipientAwardContact
keyContactsTableId=AssociateSubawardContacts
fundingAccountsTableId=AwardFundingAccounts
awardFundingAccountsTableId=SelectAwardFundingAccounts
focusAreaTableId=EnhancedGrantorAwardServiceAreas
subAwardBudgetTableId=SubAwardBudgetCategoryFlexGrid
objectivesTableId=GrantorAwardGoalsObjectives
kpiTableId=GrantorAwardKeyOutcomes
approversTableId=GrantorAwardRolesAndResponsibilities
peerReviewersTableId=GrantorAwardReviewer
peerReviewersMonitoringTableId=GrantorProgressReportReviewer
activeGrantsTableIdNew=GrantorActiveGrants
activeGrantsTableId=GrantorActiveGrants
recipientsSubawardTableId=RecipientsRelatedAwards2
pendingTaskTableId=PhasePendingTasks
grantPageTableId=flexTableDivId
paymentRequestSchedulesTableId=PaymentSchedules
progressReportScheduleTableId=TnCSchedules
riskAssessmentTableId=AwardRiskAssessmentView
riskAssessmentApproverTableId=GrantorRiskAssessmentRolesandResponsibilities
awardApproversTableId=GrantorAwardRolesAndResponsibilities
budgetLineItems=AwardLineItems
associateFocusAreaTableId=EnhancedGrantorAwardServiceAreas
associateModalTableId=SelectGATforAward
grantTermConditionPopUp=SelectAwardTermConditions
recipientsRelatedAwards2FlexToggleTableId=RecipientsRelatedAwards2FlexToggle
progressReportScheduleChildTableId=RelatedPRSchedules
progressReportScheduleId=TnCSchedules
goalsTableId=SelectAwardGoals
AwardBudgetCategoryFlexTablegridTableId=AwardBudgetCategoryFlexTable
termsndConditionsTableId=GrantorTermsandConditions
subawardFederalProgramTableId=RelatedFederalProgramForAward
sRBudgetCategoryTableId=RecipientAwardBudgetCategoryFlexGrid
#sRBudgetCategoryTableId=flexGridAwardBudgetCategoryFlexTable
RecipientAwardBudgetCategoryTableId=AwardLineItems
grantpkagestableid=GrantPackages
digiSignDivTableId=digiSignDivId
GrantBudgetCategoryFlexGridgridTableId=GrantBudgetCategoryFlexGrid
GrantorBudgetPeriodTableId=GrantorBudgetPeriod
flexGridGrantChecklistsTableId=GrantChecklists
snapshotHistoryTableId=SnapshotHistory
recipientAwardAmendmentRequestTableId=RecipientAwardAmendmentRequest
federalListTableId=SelectAwardCFDA
GrantsAttachmentTableId=GrantorGrantFiles
GrantsSubAwardsTableId=RelatedAwards1
SubAwardTableId=GrantorRelatedAwards2
RiskAttachmentFilesTableId=GrantorRiskAssessmentFiles
OrganizationRiskAssesmentFilesTableId=ExternalOrganizationRiskAssessmentFiles
RiskAssessmentPeerReviewTableId=RiskAssessmentApproverRoles
RecipientSubAwardChecklistTableId=SubRecipientAwardChecklists
RecipientSubAwardChecklistTableFrameId=SubRecipientAwardChecklistsiframeContentId
subawardOwnerTableId=GrantorAwardOwnerRoles
grantSourceOwnerTableId=GrantSourceOwnerReplace
grantTargetOwnerTableId=GrantTargetOwnerReplace
historyTableId=History
subawardTwoTableId=GrantorRelatedAwards2
grantSupportDocTableId=GrantChecklists
supdocIframeId=GrantChecklistsiframeContentId
associateTermsTableId=popupflextable
notesAwardTableId=AwardContentNote
addFilesTableId=SubawardGrantFiles
paymentSummaryBudgetTableId=PaymentRequestSummary
subrecipientFocusAreaTableId=RecipentAwardServiceAreas
addLinesBudgetCategoryTableId=AwardLineItems
paymentSummaryFocusAreaTableid=GrantBudgetCategoryActuals
grantsBudgetSummaryFocusAreaTableId=BudgetsummarybyfocusArea
subrecipientGrantActualSummaryBudgetTableId=RecipientBudgetCategoryActuals
subrecipientGrantBudgetTableId=RecGrantBudgetCategoryFlexTable
grantSubrecipientFocusAreaTableId=RecipientsGrantFocusAreas
awardPaymentSummaryFocusAreaTableId=PaymentSummarybyFocusArea
grantActualsTabFocusAreaTableId=GrantPaymentSummarybyFocusArea
recipientGrantPackageTableId=RecipientsGrantPackages
awardActualsTabFundingAccountTableId=AwardFundingAccountsActuals
FundingAccountActualsTableId=AwardFundingAccountsActuals
grantsPaymentSummaryBudgetTableId=RecipientBudgetPeriodsActualsFlexToggle
grantsBudgetCategoryTableIdSubrecipient=RecGrantBudgetCategoryFlexTable
grantsBudgetCategoryGrantor=GrantBudgetCategoryFlexTable
grantRequestTabAmendmentTableId=GrantAmendmentRequestReport
subrecipientPendingtaskTableId=PhasePendingTasks
AssociateFocusArea=SelectGATforAward
previewPackageTableId=PreviewPackageForms
subRecipientGrantBudgetTableId=RecGrantBudgetCategoryFlexGrid
GrantsAllTableId=GrantorActiveGrants
projectID=NYSED_Project_ID__c
awardProfessionalSalariesTableID=AwardProfessionalSalariesLineItems
SubrecipientAwardNotesTableId=SubrecipientAwardContentNotes
KeyPerformanceIndicatorsKPITableId=RecipentAwardKeyOutcomes
SupportStaffSalariesTableId=AwardSupportStaffSalariesLineItems
PurchasedServicesTableId=AwardPurchasedServicesLineItems
SuppliesAndMaterialsTableId=AwardSuppliesAndMaterialsLineItems
AwardTravelExpensesTableId=AwardTravelExpensesLineItems
AwardEmployeeBenefitsTableId=AwardEmployeeBenefitsLineItems
AwardIndirectCostTableId=AwardIndirectCostLineItems
AwardBOCESPurchasedServicesTableId=AwardBOCESPurchasedServicesLineItems
AwardMinorRemodelingTableId=AwardMinorRemodelingLineItems
AwardEquipmentTableId=AwardEquipmentLineItems
RecipientGoalsandObjectives=RecipientAwardGoalsObjectives
GrantorGrantsTableId=ActiveGrants

